apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: E:\KULIAH\Magang Eka Rahadi\CDC docker-compose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-connect
  name: kafka-connect
spec:
  ports:
  - name: kafka-connect
    port: 8083
    targetPort: 8083
  selector:
    io.kompose.service: kafka-connect
status:
  loadBalancer: {}
