apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  labels:
    app: kafka-connect
spec:
  ports:
    - name: kafka-connect
      port: 8083
      targetPort: 8083
  # clusterIP: None
  type: LoadBalancer
  selector:
    app: kafka-connect
