apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: E:\KULIAH\Magang Eka Rahadi\CDC docker-compose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-connect
  name: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-connect
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: E:\KULIAH\Magang Eka Rahadi\CDC docker-compose\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-connect
    spec:
      containers:
      - args:
        - bash
        - -c
        - |
          echo "Installing Connector"
          confluent-hub install --no-prompt mongodb/kafka-connect-mongodb:1.4.0
          #
          echo "Launching Kafka Connect worker"
          /etc/confluent/docker/run &
          #
          sleep infinity
        env:
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: broker:29092
        - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: _connect-configs
        - name: CONNECT_GROUP_ID
          value: kafka-connect
        - name: CONNECT_KEY_CONVERTER
          value: org.apache.kafka.connect.storage.StringConverter
        - name: CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN
          value: '[%d] %p %X{connector.context}%m (%c:%L)%n'
        - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: _connect-offsets
        - name: CONNECT_PLUGIN_PATH
          value: /usr/share/java,/usr/share/confluent-hub-components,/data/connect-jars
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          value: kafka-connect
        - name: CONNECT_REST_PORT
          value: "8083"
        - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: _connect-status
        - name: CONNECT_VALUE_CONVERTER
          value: io.confluent.connect.avro.AvroConverter
        - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
          value: http://schema-registry:8081
        image: confluentinc/cp-kafka-connect-base:6.0.1
        imagePullPolicy: ""
        name: kafka-connect
        ports:
        - containerPort: 8083
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: E
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: E
        persistentVolumeClaim:
          claimName: E
status: {}
