apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow-mongodb-consumer
parameters:
  type: pd-standard
  fstype: ext4
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
