apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  ports:
    - name: broker
      port: 29092
      targetPort: 29092
    - name: broker-host
      port: 9092
      targetPort: 9092
  clusterIP: None
  selector:
    app: broker
