apiVersion: v1
kind: Service
metadata:
  name: schema-registry
spec:
  ports:
    - name: schema-registry
      port: 8081
      targetPort: 8081
  # clusterIP: None
  type: LoadBalancer
  selector:
    app: schema-registry
