apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: E:\KULIAH\Magang Eka Rahadi\CDC docker-compose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: schema-registry
  name: schema-registry
spec:
  ports:
  - name: schema-registry
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: schema-registry
