apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: 'E:\KULIAH\Magang Eka Rahadi\CDC docker-compose\kompose.exe convert'
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper
  template:
    metadata:
      annotations:
        kompose.cmd: 'E:\KULIAH\Magang Eka Rahadi\CDC docker-compose\kompose.exe convert'
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: zookeeper
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          image: confluentinc/cp-zookeeper:6.1.0
          ports:
            - containerPort: 2181
          volumeMounts:
            - name: zookeeper-data
              mountPath: /var/lib/kafka/data
          name: zookeeper
      restartPolicy: Always
      volumeClaimTemplates:
        - metadata:
            name: zookeper-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: slow-zookeeper
        resources:
          requests:
            storage: 1Gi
