apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow-mongodb
parameters:
  type: pd-standard
  fstype: NTFS
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
